# Generated by Django 5.0.1 on 2024-02-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
